include:
  - board: nice_nano_v2@zmk
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="Settings Reset"
    artifact-name: settings_reset
  - board: nice_nano_v2@zmk
    shield: corne_left
    artifact-name: corne_left
  - board: nice_nano_v2@zmk
    shield: corne_right
    artifact-name: corne_right
